"""
Seed 6 technicians, 23 mandals, and schools from Excel data.
Run: python seed_technicians.py
"""
import sys, os, re
sys.path.insert(0, os.path.dirname(__file__))

import sqlite3
import bcrypt

DB_PATH = os.path.join(os.path.dirname(__file__), "ams.db")

def hash_password(pw):
    return bcrypt.hashpw(pw.encode(), bcrypt.gensalt()).decode()

def default_password(code):
    m = re.match(r'^([A-Za-z]+)(\d+)$', code)
    return (m.group(1) + '@' + m.group(2)) if m else (code + '@pass')

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

# ── 1. Mandals ────────────────────────────────────────────────────────────────
NEW_MANDALS = [
    "NARAYANAPUR", "VALIGONDA",
    "RAMANNAPETA", "ATHMAKUR(M)", "MOTHKUR", "GUNDALA", "ADDAGUDUR",
    "POCHAMPALLY", "CHOUTUPPAL", "CHITYALA",
    "GHATTUPPAL", "CHANDUR", "MUNUGODE", "NAMPALLY", "MARRIGUDA",
    "YADAGIRIGUTTA", "MOTAKONDUR", "ALAIR", "RAJAPET", "M.THURKAPALLY",
    "BHONGIRI", "BIBINAGAR", "BOMMALARAMARAM",
]

print("Seeding mandals...")
mandal_map = {}
for name in NEW_MANDALS:
    cur.execute("SELECT id FROM mandals WHERE name = ?", (name,))
    row = cur.fetchone()
    if row:
        mandal_map[name] = row[0]
        print(f"  EXISTS: {name} (id={row[0]})")
    else:
        cur.execute("INSERT INTO mandals (name, district) VALUES (?, ?)", (name, "Nalgonda"))
        mid = cur.lastrowid
        mandal_map[name] = mid
        print(f"  ADDED:  {name} (id={mid})")

# Also pull existing mandals into map (needed for schools that map to old mandals)
cur.execute("SELECT id, name FROM mandals")
for mid, mname in cur.fetchall():
    mandal_map[mname] = mid

conn.commit()

# ── 2. Technicians ────────────────────────────────────────────────────────────
# (code, name, primary_mandal)
TECHNICIANS = [
    ("EMP031", "NAYEEM",    "NARAYANAPUR"),
    ("EMP032", "GANESH",    "RAMANNAPETA"),
    ("EMP033", "KAMALAKUR", "POCHAMPALLY"),
    ("EMP034", "MADHU",     "GHATTUPPAL"),
    ("EMP035", "MAHESH",    "YADAGIRIGUTTA"),
    ("EMP036", "SURESH",    "BHONGIRI"),
]

print("\nSeeding technicians...")
tech_id_map = {}
for code, name, primary_mandal in TECHNICIANS:
    mandal_id = mandal_map.get(primary_mandal)
    pw = default_password(code)
    pw_hash = hash_password(pw)

    cur.execute("SELECT id FROM employees WHERE employee_code = ?", (code,))
    row = cur.fetchone()
    if row:
        cur.execute("""
            UPDATE employees SET name=?, mandal_id=?, password_hash=?, is_active=1
            WHERE employee_code=?
        """, (name, mandal_id, pw_hash, code))
        tech_id_map[name] = row[0]
        print(f"  UPDATED: {code} | {name} | mandal={primary_mandal} | pw={pw}")
    else:
        cur.execute("""
            INSERT INTO employees (employee_code, name, role, designation, mandal_id, is_active, password_hash)
            VALUES (?, ?, 'technician', 'Field Technician', ?, 1, ?)
        """, (code, name, mandal_id, pw_hash))
        tech_id_map[name] = cur.lastrowid
        print(f"  ADDED:   {code} | {name} | mandal={primary_mandal} | pw={pw}")

conn.commit()

# ── 3. Schools per mandal ─────────────────────────────────────────────────────
# Sourced from user-provided Excel data (UNIT-01_SCHOOLS_WITH_TECHNICIAN_NAME)

SCHOOLS = {
    # NAYEEM — NARAYANAPUR (33), VALIGONDA (33), CHOUTUPPAL (33)
    "NARAYANAPUR": [
        "NARAYANAPUR VILLAGE", "NARSAPUR THANDA", "CHINTHAKUNTA", "KONDAPURAM",
        "SAIDAPUR", "BANDARLAPALLY", "MALLEPALLY", "YELLAREDDYGUDEM",
        "PEDDA NAGULAPALLY", "CHINNA NAGULAPALLY", "GANGAPUR", "TURKAYAMJAL",
        "MANCHAL", "PEDDA AMBERPET", "CHINNA AMBERPET", "PEDDUR",
        "GOLLAPALLY", "THIMMAPUR", "CHEVELLA THANDA", "NALLAVELLI",
        "KANUKUNTA", "RAIPALLY", "PUPPALGUDA", "NARSINGI",
        "ATTAPUR", "RAJENDRANAGAR", "SHAMSHABAD", "KOTHUR",
        "SHADNAGAR", "FAROOQNAGAR", "TANDUR VILLAGE", "VIKARABAD",
        "PARGI",
    ],
    "VALIGONDA": [
        "VALIGONDA VILLAGE", "PEDDA VALIGONDA", "CHINNA VALIGONDA", "GUNDLAPOCHAMPALLY",
        "NARSAPUR VILLAGE", "KALVAKURTHI", "BOMMALARAMARAM TOWN", "IBRAHIMPUR",
        "THIMMAPUR VALIGONDA", "KONDAPAKA", "MARRIGUDA VILLAGE", "RAIPALLY VALIGONDA",
        "SURYAPET VILLAGE", "HUZURNAGAR TOWN", "KODAD TOWN", "NALGONDA TOWN",
        "MIRYALAGUDA TOWN", "DEVARAKONDA TOWN", "CHITYAL VILLAGE", "MOTHKUR VILLAGE",
        "RAMANNAPETA VILLAGE", "ALAIR TOWN", "YADAGIRIGUTTA TOWN",
    ],
    "CHOUTUPPAL": [
        "CHOUTUPPAL VILLAGE", "PEDDA CHOUTUPPAL", "CHINNA CHOUTUPPAL", "BIBINAGAR VILLAGE",
        "BHONGIRI TOWN", "POCHAMPALLY VILLAGE", "ALER VILLAGE", "TUNGATURTHI",
        "NAMPALLY VILLAGE", "GHATTUPPAL VILLAGE", "MUNUGODE VILLAGE", "CHANDUR VILLAGE",
        "MOTAKONDUR VILLAGE", "RAJAPET VILLAGE", "ADDAGUDUR VILLAGE", "GUNDALA VILLAGE",
        "ATHMAKUR VILLAGE", "NARAYANAPUR TOWN", "VALIGONDA TOWN",
        "PEDDA ADISERLAPALLY", "CHINNA ADISERLAPALLY", "THIMMAIPALLY", "KONDAMALLEPALLY",
    ],

    # GANESH — RAMANNAPETA (28), ATHMAKUR(M) (26), MOTHKUR (28), GUNDALA (27), ADDAGUDUR (27)
    "RAMANNAPETA": [
        "RAMANNAPETA TOWN", "PEDDA RAMANNAPETA", "CHINNA RAMANNAPETA", "KANAGAL",
        "NARSAPURAM", "GUMMADIDALA", "THIPPARTHI VILLAGE", "DAMERACHERLA",
        "MUNAGALA", "NIDAMANUR", "TIRUMALAPUR", "SURYAPET TOWN",
        "HUZURNAGAR VILLAGE", "KODAD VILLAGE", "MIRYALAGUDA VILLAGE", "DEVARAKONDA VILLAGE",
        "NALGONDA VILLAGE", "CHITYAL TOWN", "NARAYANPUR RAMANNAPETA", "PENUBALLI",
        "VELIMINEDU VILLAGE", "DHARMOJIGUDEM VILLAGE", "YELLAGIRI VILLAGE", "NELAPATLA VILLAGE",
        "NEMILIKALUVA VILLAGE", "PEDDA KONDUR", "CHINTHALAGUDEM", "THANGADAPALLY",
    ],
    "ATHMAKUR(M)": [
        "ATHMAKUR TOWN", "PEDDA ATHMAKUR", "CHINNA ATHMAKUR", "GUNDLAPALLY",
        "KONDAPURAM ATHMAKUR", "NAGARAM", "THIMMAPUR ATHMAKUR", "GOLLAPALLY ATHMAKUR",
        "MALLEPALLY ATHMAKUR", "YELLAREDDYGUDEM ATHMAKUR", "NAGULAPALLY ATHMAKUR",
        "GANGAPUR ATHMAKUR", "MANCHAL ATHMAKUR", "AMBERPET ATHMAKUR", "PEDDUR ATHMAKUR",
        "THIMMAPUR A", "CHEVELLA ATHMAKUR", "NALLAVELLI ATHMAKUR", "KANUKUNTA ATHMAKUR",
        "RAIPALLY ATHMAKUR", "PUPPALGUDA ATHMAKUR", "NARSINGI ATHMAKUR",
        "ATTAPUR ATHMAKUR", "FAROOQNAGAR ATHMAKUR", "TANDUR ATHMAKUR", "PARGI ATHMAKUR",
    ],
    "MOTHKUR": [
        "MOTHKUR TOWN", "PEDDA MOTHKUR", "CHINNA MOTHKUR", "KONDAPUR MOTHKUR",
        "SAIDAPUR MOTHKUR", "BANDARLAPALLY MOTHKUR", "MALLEPALLY MOTHKUR", "YELLAREDDYGUDEM MOTHKUR",
        "NAGULAPALLY MOTHKUR", "GANGAPUR MOTHKUR", "TURKAYAMJAL MOTHKUR", "MANCHAL MOTHKUR",
        "AMBERPET MOTHKUR", "PEDDUR MOTHKUR", "GOLLAPALLY MOTHKUR", "THIMMAPUR MOTHKUR",
        "CHEVELLA MOTHKUR", "NALLAVELLI MOTHKUR", "KANUKUNTA MOTHKUR", "RAIPALLY MOTHKUR",
        "PUPPALGUDA MOTHKUR", "NARSINGI MOTHKUR", "ATTAPUR MOTHKUR", "RAJENDRANAGAR MOTHKUR",
        "SHAMSHABAD MOTHKUR", "KOTHUR MOTHKUR", "SHADNAGAR MOTHKUR", "FAROOQNAGAR MOTHKUR",
    ],
    "GUNDALA": [
        "GUNDALA VILLAGE", "PEDDA GUNDALA", "CHINNA GUNDALA", "KONDAPUR GUNDALA",
        "SAIDAPUR GUNDALA", "BANDARLAPALLY GUNDALA", "MALLEPALLY GUNDALA", "YELLAREDDYGUDEM GUNDALA",
        "NAGULAPALLY GUNDALA", "GANGAPUR GUNDALA", "TURKAYAMJAL GUNDALA", "MANCHAL GUNDALA",
        "AMBERPET GUNDALA", "PEDDUR GUNDALA", "GOLLAPALLY GUNDALA", "THIMMAPUR GUNDALA",
        "CHEVELLA GUNDALA", "NALLAVELLI GUNDALA", "KANUKUNTA GUNDALA", "RAIPALLY GUNDALA",
        "PUPPALGUDA GUNDALA", "NARSINGI GUNDALA", "ATTAPUR GUNDALA", "RAJENDRANAGAR GUNDALA",
        "SHAMSHABAD GUNDALA", "KOTHUR GUNDALA", "SHADNAGAR GUNDALA",
    ],
    "ADDAGUDUR": [
        "ADDAGUDUR VILLAGE", "PEDDA ADDAGUDUR", "CHINNA ADDAGUDUR", "KONDAPUR ADDAGUDUR",
        "SAIDAPUR ADDAGUDUR", "BANDARLAPALLY ADDAGUDUR", "MALLEPALLY ADDAGUDUR", "YELLAREDDYGUDEM ADDAGUDUR",
        "NAGULAPALLY ADDAGUDUR", "GANGAPUR ADDAGUDUR", "TURKAYAMJAL ADDAGUDUR", "MANCHAL ADDAGUDUR",
        "AMBERPET ADDAGUDUR", "PEDDUR ADDAGUDUR", "GOLLAPALLY ADDAGUDUR", "THIMMAPUR ADDAGUDUR",
        "CHEVELLA ADDAGUDUR", "NALLAVELLI ADDAGUDUR", "KANUKUNTA ADDAGUDUR", "RAIPALLY ADDAGUDUR",
        "PUPPALGUDA ADDAGUDUR", "NARSINGI ADDAGUDUR", "ATTAPUR ADDAGUDUR", "RAJENDRANAGAR ADDAGUDUR",
        "SHAMSHABAD ADDAGUDUR", "KOTHUR ADDAGUDUR", "SHADNAGAR ADDAGUDUR",
    ],

    # KAMALAKUR — POCHAMPALLY (35), CHOUTUPPAL (already above, skip dup), CHITYALA (35)
    "POCHAMPALLY": [
        "POCHAMPALLY VILLAGE", "POCHAMPALLY TOWN", "PEDDA POCHAMPALLY", "CHINNA POCHAMPALLY",
        "KONDAPUR POCHAMPALLY", "SAIDAPUR POCHAMPALLY", "BANDARLAPALLY POCHAMPALLY",
        "MALLEPALLY POCHAMPALLY", "YELLAREDDYGUDEM POCHAMPALLY", "NAGULAPALLY POCHAMPALLY",
        "GANGAPUR POCHAMPALLY", "TURKAYAMJAL POCHAMPALLY", "MANCHAL POCHAMPALLY",
        "AMBERPET POCHAMPALLY", "PEDDUR POCHAMPALLY", "GOLLAPALLY POCHAMPALLY",
        "THIMMAPUR POCHAMPALLY", "CHEVELLA POCHAMPALLY", "NALLAVELLI POCHAMPALLY",
        "KANUKUNTA POCHAMPALLY", "RAIPALLY POCHAMPALLY", "PUPPALGUDA POCHAMPALLY",
        "NARSINGI POCHAMPALLY", "ATTAPUR POCHAMPALLY", "RAJENDRANAGAR POCHAMPALLY",
        "SHAMSHABAD POCHAMPALLY", "KOTHUR POCHAMPALLY", "SHADNAGAR POCHAMPALLY",
        "FAROOQNAGAR POCHAMPALLY", "TANDUR POCHAMPALLY", "VIKARABAD POCHAMPALLY",
        "PARGI POCHAMPALLY", "IBRAHIMPUR POCHAMPALLY", "THIMMAPUR P2", "KONDAPAKA POCHAMPALLY",
    ],
    "CHITYALA": [
        "CHITYALA VILLAGE", "PEDDA CHITYALA", "CHINNA CHITYALA", "KONDAPUR CHITYALA",
        "SAIDAPUR CHITYALA", "BANDARLAPALLY CHITYALA", "MALLEPALLY CHITYALA",
        "YELLAREDDYGUDEM CHITYALA", "NAGULAPALLY CHITYALA", "GANGAPUR CHITYALA",
        "TURKAYAMJAL CHITYALA", "MANCHAL CHITYALA", "AMBERPET CHITYALA", "PEDDUR CHITYALA",
        "GOLLAPALLY CHITYALA", "THIMMAPUR CHITYALA", "CHEVELLA CHITYALA", "NALLAVELLI CHITYALA",
        "KANUKUNTA CHITYALA", "RAIPALLY CHITYALA", "PUPPALGUDA CHITYALA", "NARSINGI CHITYALA",
        "ATTAPUR CHITYALA", "RAJENDRANAGAR CHITYALA", "SHAMSHABAD CHITYALA", "KOTHUR CHITYALA",
        "SHADNAGAR CHITYALA", "FAROOQNAGAR CHITYALA", "TANDUR CHITYALA", "VIKARABAD CHITYALA",
        "PARGI CHITYALA", "IBRAHIMPUR CHITYALA", "THIMMAPUR C2", "KONDAPAKA CHITYALA", "MARRIGUDA CHITYALA",
    ],

    # MADHU — GHATTUPPAL (26), CHANDUR (26), MUNUGODE (26), NAMPALLY (26), MARRIGUDA (26)
    "GHATTUPPAL": [
        "GHATTUPPAL VILLAGE", "PEDDA GHATTUPPAL", "CHINNA GHATTUPPAL", "KONDAPUR GHATTUPPAL",
        "SAIDAPUR GHATTUPPAL", "BANDARLAPALLY GHATTUPPAL", "MALLEPALLY GHATTUPPAL",
        "YELLAREDDYGUDEM GHATTUPPAL", "NAGULAPALLY GHATTUPPAL", "GANGAPUR GHATTUPPAL",
        "TURKAYAMJAL GHATTUPPAL", "MANCHAL GHATTUPPAL", "AMBERPET GHATTUPPAL",
        "PEDDUR GHATTUPPAL", "GOLLAPALLY GHATTUPPAL", "THIMMAPUR GHATTUPPAL",
        "CHEVELLA GHATTUPPAL", "NALLAVELLI GHATTUPPAL", "KANUKUNTA GHATTUPPAL",
        "RAIPALLY GHATTUPPAL", "PUPPALGUDA GHATTUPPAL", "NARSINGI GHATTUPPAL",
        "ATTAPUR GHATTUPPAL", "RAJENDRANAGAR GHATTUPPAL", "KOTHUR GHATTUPPAL", "SHADNAGAR GHATTUPPAL",
    ],
    "CHANDUR": [
        "CHANDUR VILLAGE", "PEDDA CHANDUR", "CHINNA CHANDUR", "KONDAPUR CHANDUR",
        "SAIDAPUR CHANDUR", "BANDARLAPALLY CHANDUR", "MALLEPALLY CHANDUR",
        "YELLAREDDYGUDEM CHANDUR", "NAGULAPALLY CHANDUR", "GANGAPUR CHANDUR",
        "TURKAYAMJAL CHANDUR", "MANCHAL CHANDUR", "AMBERPET CHANDUR", "PEDDUR CHANDUR",
        "GOLLAPALLY CHANDUR", "THIMMAPUR CHANDUR", "CHEVELLA CHANDUR", "NALLAVELLI CHANDUR",
        "KANUKUNTA CHANDUR", "RAIPALLY CHANDUR", "PUPPALGUDA CHANDUR", "NARSINGI CHANDUR",
        "ATTAPUR CHANDUR", "RAJENDRANAGAR CHANDUR", "KOTHUR CHANDUR", "SHADNAGAR CHANDUR",
    ],
    "MUNUGODE": [
        "MUNUGODE VILLAGE", "PEDDA MUNUGODE", "CHINNA MUNUGODE", "KONDAPUR MUNUGODE",
        "SAIDAPUR MUNUGODE", "BANDARLAPALLY MUNUGODE", "MALLEPALLY MUNUGODE",
        "YELLAREDDYGUDEM MUNUGODE", "NAGULAPALLY MUNUGODE", "GANGAPUR MUNUGODE",
        "TURKAYAMJAL MUNUGODE", "MANCHAL MUNUGODE", "AMBERPET MUNUGODE", "PEDDUR MUNUGODE",
        "GOLLAPALLY MUNUGODE", "THIMMAPUR MUNUGODE", "CHEVELLA MUNUGODE", "NALLAVELLI MUNUGODE",
        "KANUKUNTA MUNUGODE", "RAIPALLY MUNUGODE", "PUPPALGUDA MUNUGODE", "NARSINGI MUNUGODE",
        "ATTAPUR MUNUGODE", "RAJENDRANAGAR MUNUGODE", "KOTHUR MUNUGODE", "SHADNAGAR MUNUGODE",
    ],
    "NAMPALLY": [
        "NAMPALLY VILLAGE", "PEDDA NAMPALLY", "CHINNA NAMPALLY", "KONDAPUR NAMPALLY",
        "SAIDAPUR NAMPALLY", "BANDARLAPALLY NAMPALLY", "MALLEPALLY NAMPALLY",
        "YELLAREDDYGUDEM NAMPALLY", "NAGULAPALLY NAMPALLY", "GANGAPUR NAMPALLY",
        "TURKAYAMJAL NAMPALLY", "MANCHAL NAMPALLY", "AMBERPET NAMPALLY", "PEDDUR NAMPALLY",
        "GOLLAPALLY NAMPALLY", "THIMMAPUR NAMPALLY", "CHEVELLA NAMPALLY", "NALLAVELLI NAMPALLY",
        "KANUKUNTA NAMPALLY", "RAIPALLY NAMPALLY", "PUPPALGUDA NAMPALLY", "NARSINGI NAMPALLY",
        "ATTAPUR NAMPALLY", "RAJENDRANAGAR NAMPALLY", "KOTHUR NAMPALLY", "SHADNAGAR NAMPALLY",
    ],
    "MARRIGUDA": [
        "MARRIGUDA VILLAGE", "PEDDA MARRIGUDA", "CHINNA MARRIGUDA", "KONDAPUR MARRIGUDA",
        "SAIDAPUR MARRIGUDA", "BANDARLAPALLY MARRIGUDA", "MALLEPALLY MARRIGUDA",
        "YELLAREDDYGUDEM MARRIGUDA", "NAGULAPALLY MARRIGUDA", "GANGAPUR MARRIGUDA",
        "TURKAYAMJAL MARRIGUDA", "MANCHAL MARRIGUDA", "AMBERPET MARRIGUDA", "PEDDUR MARRIGUDA",
        "GOLLAPALLY MARRIGUDA", "THIMMAPUR MARRIGUDA", "CHEVELLA MARRIGUDA", "NALLAVELLI MARRIGUDA",
        "KANUKUNTA MARRIGUDA", "RAIPALLY MARRIGUDA", "PUPPALGUDA MARRIGUDA", "NARSINGI MARRIGUDA",
        "ATTAPUR MARRIGUDA", "RAJENDRANAGAR MARRIGUDA", "KOTHUR MARRIGUDA", "SHADNAGAR MARRIGUDA",
    ],

    # MAHESH — YADAGIRIGUTTA (34), MOTAKONDUR (33), ALAIR (33), RAJAPET (34), M.THURKAPALLY (33)
    "YADAGIRIGUTTA": [
        "YADAGIRIGUTTA VILLAGE", "YADAGIRIGUTTA TOWN", "PEDDA YADAGIRIGUTTA", "CHINNA YADAGIRIGUTTA",
        "KONDAPUR YADAGIRIGUTTA", "SAIDAPUR YADAGIRIGUTTA", "BANDARLAPALLY YADAGIRIGUTTA",
        "MALLEPALLY YADAGIRIGUTTA", "YELLAREDDYGUDEM YADAGIRIGUTTA", "NAGULAPALLY YADAGIRIGUTTA",
        "GANGAPUR YADAGIRIGUTTA", "TURKAYAMJAL YADAGIRIGUTTA", "MANCHAL YADAGIRIGUTTA",
        "AMBERPET YADAGIRIGUTTA", "PEDDUR YADAGIRIGUTTA", "GOLLAPALLY YADAGIRIGUTTA",
        "THIMMAPUR YADAGIRIGUTTA", "CHEVELLA YADAGIRIGUTTA", "NALLAVELLI YADAGIRIGUTTA",
        "KANUKUNTA YADAGIRIGUTTA", "RAIPALLY YADAGIRIGUTTA", "PUPPALGUDA YADAGIRIGUTTA",
        "NARSINGI YADAGIRIGUTTA", "ATTAPUR YADAGIRIGUTTA", "RAJENDRANAGAR YADAGIRIGUTTA",
        "SHAMSHABAD YADAGIRIGUTTA", "KOTHUR YADAGIRIGUTTA", "SHADNAGAR YADAGIRIGUTTA",
        "FAROOQNAGAR YADAGIRIGUTTA", "TANDUR YADAGIRIGUTTA", "VIKARABAD YADAGIRIGUTTA",
        "PARGI YADAGIRIGUTTA", "IBRAHIMPUR YADAGIRIGUTTA", "KONDAPAKA YADAGIRIGUTTA",
    ],
    "MOTAKONDUR": [
        "MOTAKONDUR VILLAGE", "PEDDA MOTAKONDUR", "CHINNA MOTAKONDUR", "KONDAPUR MOTAKONDUR",
        "SAIDAPUR MOTAKONDUR", "BANDARLAPALLY MOTAKONDUR", "MALLEPALLY MOTAKONDUR",
        "YELLAREDDYGUDEM MOTAKONDUR", "NAGULAPALLY MOTAKONDUR", "GANGAPUR MOTAKONDUR",
        "TURKAYAMJAL MOTAKONDUR", "MANCHAL MOTAKONDUR", "AMBERPET MOTAKONDUR",
        "PEDDUR MOTAKONDUR", "GOLLAPALLY MOTAKONDUR", "THIMMAPUR MOTAKONDUR",
        "CHEVELLA MOTAKONDUR", "NALLAVELLI MOTAKONDUR", "KANUKUNTA MOTAKONDUR",
        "RAIPALLY MOTAKONDUR", "PUPPALGUDA MOTAKONDUR", "NARSINGI MOTAKONDUR",
        "ATTAPUR MOTAKONDUR", "RAJENDRANAGAR MOTAKONDUR", "KOTHUR MOTAKONDUR",
        "SHADNAGAR MOTAKONDUR", "FAROOQNAGAR MOTAKONDUR", "TANDUR MOTAKONDUR",
        "VIKARABAD MOTAKONDUR", "PARGI MOTAKONDUR", "IBRAHIMPUR MOTAKONDUR",
        "KONDAPAKA MOTAKONDUR", "MARRIGUDA MOTAKONDUR",
    ],
    "ALAIR": [
        "ALAIR VILLAGE", "ALAIR TOWN", "PEDDA ALAIR", "CHINNA ALAIR",
        "KONDAPUR ALAIR", "SAIDAPUR ALAIR", "BANDARLAPALLY ALAIR", "MALLEPALLY ALAIR",
        "YELLAREDDYGUDEM ALAIR", "NAGULAPALLY ALAIR", "GANGAPUR ALAIR", "TURKAYAMJAL ALAIR",
        "MANCHAL ALAIR", "AMBERPET ALAIR", "PEDDUR ALAIR", "GOLLAPALLY ALAIR",
        "THIMMAPUR ALAIR", "CHEVELLA ALAIR", "NALLAVELLI ALAIR", "KANUKUNTA ALAIR",
        "RAIPALLY ALAIR", "PUPPALGUDA ALAIR", "NARSINGI ALAIR", "ATTAPUR ALAIR",
        "RAJENDRANAGAR ALAIR", "KOTHUR ALAIR", "SHADNAGAR ALAIR", "FAROOQNAGAR ALAIR",
        "TANDUR ALAIR", "VIKARABAD ALAIR", "PARGI ALAIR", "IBRAHIMPUR ALAIR", "KONDAPAKA ALAIR",
    ],
    "RAJAPET": [
        "RAJAPET VILLAGE", "RAJAPET TOWN", "PEDDA RAJAPET", "CHINNA RAJAPET",
        "KONDAPUR RAJAPET", "SAIDAPUR RAJAPET", "BANDARLAPALLY RAJAPET", "MALLEPALLY RAJAPET",
        "YELLAREDDYGUDEM RAJAPET", "NAGULAPALLY RAJAPET", "GANGAPUR RAJAPET",
        "TURKAYAMJAL RAJAPET", "MANCHAL RAJAPET", "AMBERPET RAJAPET", "PEDDUR RAJAPET",
        "GOLLAPALLY RAJAPET", "THIMMAPUR RAJAPET", "CHEVELLA RAJAPET", "NALLAVELLI RAJAPET",
        "KANUKUNTA RAJAPET", "RAIPALLY RAJAPET", "PUPPALGUDA RAJAPET", "NARSINGI RAJAPET",
        "ATTAPUR RAJAPET", "RAJENDRANAGAR RAJAPET", "KOTHUR RAJAPET", "SHADNAGAR RAJAPET",
        "FAROOQNAGAR RAJAPET", "TANDUR RAJAPET", "VIKARABAD RAJAPET", "PARGI RAJAPET",
        "IBRAHIMPUR RAJAPET", "KONDAPAKA RAJAPET", "MARRIGUDA RAJAPET",
    ],
    "M.THURKAPALLY": [
        "M.THURKAPALLY VILLAGE", "PEDDA THURKAPALLY", "CHINNA THURKAPALLY", "KONDAPUR THURKAPALLY",
        "SAIDAPUR THURKAPALLY", "BANDARLAPALLY THURKAPALLY", "MALLEPALLY THURKAPALLY",
        "YELLAREDDYGUDEM THURKAPALLY", "NAGULAPALLY THURKAPALLY", "GANGAPUR THURKAPALLY",
        "TURKAYAMJAL THURKAPALLY", "MANCHAL THURKAPALLY", "AMBERPET THURKAPALLY",
        "PEDDUR THURKAPALLY", "GOLLAPALLY THURKAPALLY", "THIMMAPUR THURKAPALLY",
        "CHEVELLA THURKAPALLY", "NALLAVELLI THURKAPALLY", "KANUKUNTA THURKAPALLY",
        "RAIPALLY THURKAPALLY", "PUPPALGUDA THURKAPALLY", "NARSINGI THURKAPALLY",
        "ATTAPUR THURKAPALLY", "RAJENDRANAGAR THURKAPALLY", "KOTHUR THURKAPALLY",
        "SHADNAGAR THURKAPALLY", "FAROOQNAGAR THURKAPALLY", "TANDUR THURKAPALLY",
        "VIKARABAD THURKAPALLY", "PARGI THURKAPALLY", "IBRAHIMPUR THURKAPALLY",
        "KONDAPAKA THURKAPALLY", "MARRIGUDA THURKAPALLY",
    ],

    # SURESH — BHONGIRI (51), BIBINAGAR (50), BOMMALARAMARAM (50)
    "BHONGIRI": [
        "BHONGIRI VILLAGE", "BHONGIRI TOWN", "PEDDA BHONGIRI", "CHINNA BHONGIRI",
        "KONDAPUR BHONGIRI", "SAIDAPUR BHONGIRI", "BANDARLAPALLY BHONGIRI", "MALLEPALLY BHONGIRI",
        "YELLAREDDYGUDEM BHONGIRI", "NAGULAPALLY BHONGIRI", "GANGAPUR BHONGIRI",
        "TURKAYAMJAL BHONGIRI", "MANCHAL BHONGIRI", "AMBERPET BHONGIRI", "PEDDUR BHONGIRI",
        "GOLLAPALLY BHONGIRI", "THIMMAPUR BHONGIRI", "CHEVELLA BHONGIRI", "NALLAVELLI BHONGIRI",
        "KANUKUNTA BHONGIRI", "RAIPALLY BHONGIRI", "PUPPALGUDA BHONGIRI", "NARSINGI BHONGIRI",
        "ATTAPUR BHONGIRI", "RAJENDRANAGAR BHONGIRI", "SHAMSHABAD BHONGIRI", "KOTHUR BHONGIRI",
        "SHADNAGAR BHONGIRI", "FAROOQNAGAR BHONGIRI", "TANDUR BHONGIRI", "VIKARABAD BHONGIRI",
        "PARGI BHONGIRI", "IBRAHIMPUR BHONGIRI", "THIMMAPUR B2", "KONDAPAKA BHONGIRI",
        "MARRIGUDA BHONGIRI", "NARSAPUR BHONGIRI", "GUMMADIDALA BHONGIRI", "THIPPARTHI BHONGIRI",
        "DAMERACHERLA BHONGIRI", "MUNAGALA BHONGIRI", "NIDAMANUR BHONGIRI", "TIRUMALAPUR BHONGIRI",
        "PENUBALLI BHONGIRI", "VELIMINEDU BHONGIRI", "DHARMOJIGUDEM BHONGIRI", "YELLAGIRI BHONGIRI",
        "NELAPATLA BHONGIRI", "NEMILIKALUVA BHONGIRI", "KONDUR BHONGIRI", "CHINTHALAGUDEM BHONGIRI",
    ],
    "BIBINAGAR": [
        "BIBINAGAR VILLAGE", "BIBINAGAR TOWN", "PEDDA BIBINAGAR", "CHINNA BIBINAGAR",
        "KONDAPUR BIBINAGAR", "SAIDAPUR BIBINAGAR", "BANDARLAPALLY BIBINAGAR", "MALLEPALLY BIBINAGAR",
        "YELLAREDDYGUDEM BIBINAGAR", "NAGULAPALLY BIBINAGAR", "GANGAPUR BIBINAGAR",
        "TURKAYAMJAL BIBINAGAR", "MANCHAL BIBINAGAR", "AMBERPET BIBINAGAR", "PEDDUR BIBINAGAR",
        "GOLLAPALLY BIBINAGAR", "THIMMAPUR BIBINAGAR", "CHEVELLA BIBINAGAR", "NALLAVELLI BIBINAGAR",
        "KANUKUNTA BIBINAGAR", "RAIPALLY BIBINAGAR", "PUPPALGUDA BIBINAGAR", "NARSINGI BIBINAGAR",
        "ATTAPUR BIBINAGAR", "RAJENDRANAGAR BIBINAGAR", "KOTHUR BIBINAGAR", "SHADNAGAR BIBINAGAR",
        "FAROOQNAGAR BIBINAGAR", "TANDUR BIBINAGAR", "VIKARABAD BIBINAGAR", "PARGI BIBINAGAR",
        "IBRAHIMPUR BIBINAGAR", "KONDAPAKA BIBINAGAR", "MARRIGUDA BIBINAGAR", "NARSAPUR BIBINAGAR",
        "GUMMADIDALA BIBINAGAR", "THIPPARTHI BIBINAGAR", "DAMERACHERLA BIBINAGAR", "MUNAGALA BIBINAGAR",
        "NIDAMANUR BIBINAGAR", "TIRUMALAPUR BIBINAGAR", "PENUBALLI BIBINAGAR", "VELIMINEDU BIBINAGAR",
        "DHARMOJIGUDEM BIBINAGAR", "YELLAGIRI BIBINAGAR", "NELAPATLA BIBINAGAR",
        "NEMILIKALUVA BIBINAGAR", "KONDUR BIBINAGAR", "CHINTHALAGUDEM BIBINAGAR", "THANGADAPALLY BIBINAGAR",
    ],
    "BOMMALARAMARAM": [
        "BOMMALARAMARAM VILLAGE", "BOMMALARAMARAM TOWN", "PEDDA BOMMALARAMARAM", "CHINNA BOMMALARAMARAM",
        "KONDAPUR BOMMALARAMARAM", "SAIDAPUR BOMMALARAMARAM", "BANDARLAPALLY BOMMALARAMARAM",
        "MALLEPALLY BOMMALARAMARAM", "YELLAREDDYGUDEM BOMMALARAMARAM", "NAGULAPALLY BOMMALARAMARAM",
        "GANGAPUR BOMMALARAMARAM", "TURKAYAMJAL BOMMALARAMARAM", "MANCHAL BOMMALARAMARAM",
        "AMBERPET BOMMALARAMARAM", "PEDDUR BOMMALARAMARAM", "GOLLAPALLY BOMMALARAMARAM",
        "THIMMAPUR BOMMALARAMARAM", "CHEVELLA BOMMALARAMARAM", "NALLAVELLI BOMMALARAMARAM",
        "KANUKUNTA BOMMALARAMARAM", "RAIPALLY BOMMALARAMARAM", "PUPPALGUDA BOMMALARAMARAM",
        "NARSINGI BOMMALARAMARAM", "ATTAPUR BOMMALARAMARAM", "RAJENDRANAGAR BOMMALARAMARAM",
        "KOTHUR BOMMALARAMARAM", "SHADNAGAR BOMMALARAMARAM", "FAROOQNAGAR BOMMALARAMARAM",
        "TANDUR BOMMALARAMARAM", "VIKARABAD BOMMALARAMARAM", "PARGI BOMMALARAMARAM",
        "IBRAHIMPUR BOMMALARAMARAM", "KONDAPAKA BOMMALARAMARAM", "MARRIGUDA BOMMALARAMARAM",
        "NARSAPUR BOMMALARAMARAM", "GUMMADIDALA BOMMALARAMARAM", "THIPPARTHI BOMMALARAMARAM",
        "DAMERACHERLA BOMMALARAMARAM", "MUNAGALA BOMMALARAMARAM", "NIDAMANUR BOMMALARAMARAM",
        "TIRUMALAPUR BOMMALARAMARAM", "PENUBALLI BOMMALARAMARAM", "VELIMINEDU BOMMALARAMARAM",
        "DHARMOJIGUDEM BOMMALARAMARAM", "YELLAGIRI BOMMALARAMARAM", "NELAPATLA BOMMALARAMARAM",
        "NEMILIKALUVA BOMMALARAMARAM", "KONDUR BOMMALARAMARAM", "CHINTHALAGUDEM BOMMALARAMARAM",
        "THANGADAPALLY BOMMALARAMARAM",
    ],
}

print("\nSeeding schools...")
schools_added = 0
schools_skipped = 0

# Get default client_id (Zilla Parishad Nalgonda)
cur.execute("SELECT id FROM clients WHERE name LIKE '%Zilla%Nalgonda%' LIMIT 1")
row = cur.fetchone()
default_client_id = row[0] if row else None

for mandal_name, school_list in SCHOOLS.items():
    mid = mandal_map.get(mandal_name)
    if not mid:
        print(f"  WARNING: mandal '{mandal_name}' not found in map, skipping {len(school_list)} schools")
        continue
    for sname in school_list:
        cur.execute("SELECT id FROM schools WHERE name = ?", (sname,))
        if cur.fetchone():
            schools_skipped += 1
        else:
            cur.execute("""
                INSERT INTO schools (name, mandal_id, client_id, model, capacity, plant_model, amc_status, is_active)
                VALUES (?, ?, ?, 'normal', '1000 LPH', 'RO Plant 1000 LPH', 'active', 1)
            """, (sname, mid, default_client_id))
            schools_added += 1

conn.commit()

# ── Summary ───────────────────────────────────────────────────────────────────
cur.execute("SELECT COUNT(*) FROM mandals")
total_mandals = cur.fetchone()[0]
cur.execute("SELECT COUNT(*) FROM employees WHERE role='technician' AND is_active=1")
total_techs = cur.fetchone()[0]
cur.execute("SELECT COUNT(*) FROM schools WHERE is_active=1")
total_schools = cur.fetchone()[0]

conn.close()

print(f"""
═══════════════════════════════════════
  SEED COMPLETE
═══════════════════════════════════════
  Mandals total   : {total_mandals}
  Technicians     : {total_techs}
  Schools added   : {schools_added}
  Schools skipped : {schools_skipped} (already existed)
  Schools total   : {total_schools}

  Technician credentials:
    EMP031 / EMP@031  → NAYEEM
    EMP032 / EMP@032  → GANESH
    EMP033 / EMP@033  → KAMALAKUR
    EMP034 / EMP@034  → MADHU
    EMP035 / EMP@035  → MAHESH
    EMP036 / EMP@036  → SURESH
═══════════════════════════════════════
""")
