import { useState, useEffect } from 'react'
import api from '../api/axios'
import SearchableSelect from '../components/SearchableSelect'

const PRIORITY_PILL = { low: 'pill-blue', medium: 'pill-yellow', high: 'pill-red' }
const STATUS_PILL   = { pending: 'pill-yellow', in_progress: 'pill-orange', submitted: 'pill-yellow', completed: 'pill-green', cancelled: 'pill-gray' }
const STATUS_ORDER  = ['pending', 'in_progress', 'submitted', 'completed']
const STATUS_LABEL  = { pending: 'Pending', in_progress: 'In Progress', submitted: 'Submitted', completed: 'Completed' }

export default function Tasks() {
  const [tasks, setTasks]         = useState([])
  const [employees, setEmployees] = useState([])
  const [loading, setLoading]     = useState(true)
  const [modal, setModal]         = useState(false)
  const [form, setForm]           = useState({ title: '', description: '', assigned_to_id: '', priority: 'medium', due_date: '' })
  const [toast, setToast]         = useState('')
  const [generating, setGenerating] = useState(false)
  const [resetStep, setResetStep]   = useState(0)   // 0=idle, 1=confirm modal, 2=resetting
  const [resetConfirmText, setResetConfirmText] = useState('')
  const [filterDate, setFilterDate] = useState('')
  const [activeTech, setActiveTech] = useState(null)
  const [techSearch, setTechSearch] = useState('')    // technician tab search
  const [taskSearch, setTaskSearch] = useState('')    // task search within technician
  const [statusFilter, setStatusFilter] = useState('')  // status filter
  const [priorityFilter, setPriorityFilter] = useState('')  // priority filter
  const today     = new Date().toISOString().slice(0, 10)
  const yesterday = new Date(Date.now() - 864e5).toISOString().slice(0, 10)

  function showToast(msg) { setToast(msg); setTimeout(() => setToast(''), 4000) }
  function f(k) { return e => setForm({ ...form, [k]: e.target.value }) }

  function load() {
    const params = new URLSearchParams()
    if (filterDate) params.append('task_date', filterDate)
    Promise.all([
      api.get(`/api/tasks/?${params}`),
      api.get('/api/employees/')
    ]).then(([t, e]) => {
      setTasks(t.data)
      const techs = e.data.filter(emp => emp.role === 'technician')
      setEmployees(e.data)
      if (!activeTech && techs.length > 0) setActiveTech(techs[0].id)
      setLoading(false)
    })
  }

  useEffect(() => { load() }, [filterDate])
  // Auto-refresh every 30 seconds to pick up tasks generated by other admins
  useEffect(() => {
    const t = setInterval(load, 30000)
    return () => clearInterval(t)
  }, [filterDate])

  async function generateDaily() {
    setGenerating(true)
    try {
      const r = await api.post('/api/tasks/generate-daily', null, { params: { task_date: today } })
      const total = r.data.results.reduce((s, x) => s + (x.generated || 0), 0)
      showToast(`Generated ${total} tasks for ${r.data.processed} technicians`)
      load()
    } catch { showToast('Failed to generate tasks') }
    setGenerating(false)
  }

  async function save(ev) {
    ev.preventDefault()
    if (!form.assigned_to_id) { showToast('❌ Select who to assign this to'); return }
    await api.post('/api/tasks/', { ...form, assigned_to_id: parseInt(form.assigned_to_id) })
    load(); setModal(false); showToast('Task created!')
  }

  async function updateStatus(id, status) {
    await api.patch(`/api/tasks/${id}/status?status=${status}`)
    load()
  }

  async function resetAllTasks() {
    setResetStep(2)
    try {
      const r = await api.delete('/api/tasks/reset-all')
      showToast(`🗑️ ${r.data.deleted} tasks deleted. Click "Generate Daily Tasks" to assign fresh tasks.`)
      load()
    } catch (e) {
      const msg = e.response?.data?.detail || e.message || 'unknown error'
      showToast(`Failed to reset tasks: ${msg}`)
    }
    setResetStep(0)
    setResetConfirmText('')
  }

  async function del(id) {
    if (!confirm('Delete task?')) return
    await api.delete(`/api/tasks/${id}`)
    setTasks(tasks.filter(t => t.id !== id))
  }

  // All technicians from employees list
  const technicians = employees.filter(e => e.role === 'technician')

  // Filtered technician tabs by search
  const visibleTechs = technicians.filter(e =>
    e.name.toLowerCase().includes(techSearch.toLowerCase()) ||
    (e.employee_code || '').toLowerCase().includes(techSearch.toLowerCase())
  )

  // Tasks for the active technician, filtered by task search + status + priority
  const techTasks = activeTech ? tasks.filter(t => {
    if (t.assigned_to_id !== activeTech) return false
    if (statusFilter && t.status !== statusFilter) return false
    if (priorityFilter && t.priority !== priorityFilter) return false
    if (taskSearch) {
      const q = taskSearch.toLowerCase()
      return (t.title || '').toLowerCase().includes(q) ||
             (t.school_name || '').toLowerCase().includes(q)
    }
    return true
  }) : []

  // Group by status — pending shows yesterday+today, submitted shows today only
  const grouped = {
    pending:     techTasks.filter(t => t.status === 'pending'     && (t.due_date === today || t.due_date === yesterday)),
    in_progress: techTasks.filter(t => t.status === 'in_progress'),
    submitted:   techTasks.filter(t => t.status === 'submitted'   && t.due_date === today),
    completed:   techTasks.filter(t => t.status === 'completed'),
  }

  // Summary counts per technician (unfiltered — always show real totals on tabs)
  const techSummary = technicians.map(tech => {
    const tt = tasks.filter(t => t.assigned_to_id === tech.id)
    return {
      ...tech,
      total: tt.length,
      pending: tt.filter(t => t.status === 'pending').length,
      in_progress: tt.filter(t => t.status === 'in_progress').length,
      submitted: tt.filter(t => t.status === 'submitted').length,
      completed: tt.filter(t => t.status === 'completed').length,
    }
  })

  if (loading) return <div className="spinner" />

  return (
    <div>
      {/* Header */}
      <div className="section-header">
        <h3>✅ Tasks</h3>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
          <input type="date" value={filterDate} onChange={e => setFilterDate(e.target.value)}
            style={{ fontSize: 12, padding: '6px 10px', background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 6, color: 'var(--text)' }} />
          {filterDate && <button className="btn btn-outline btn-sm" onClick={() => setFilterDate('')}>Clear</button>}
          <button className="btn btn-primary" style={{ background: 'var(--green)', fontSize: 12 }}
            onClick={generateDaily} disabled={generating}>
            {generating ? '⏳ Generating…' : '⚡ Generate Daily Tasks'}
          </button>
          <button className="btn btn-danger" style={{ fontSize: 12 }}
            onClick={() => { setResetStep(1); setResetConfirmText('') }}
            disabled={resetStep === 2}>
            🗑️ Reset All Tasks
          </button>
          <button className="btn btn-primary" onClick={() => setModal(true)}>+ Create Task</button>
        </div>
      </div>

      {/* Technician search + tabs */}
      <div className="card" style={{ marginBottom: 16, padding: '12px 14px' }}>
        <div style={{ marginBottom: 10 }}>
          <input
            placeholder="🔍 Search technician by name or ID..."
            value={techSearch}
            onChange={e => setTechSearch(e.target.value)}
            style={{ width: '100%', boxSizing: 'border-box', padding: '8px 12px', fontSize: 13,
              background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 8, color: 'var(--text)' }}
          />
        </div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {visibleTechs.length === 0 && (
            <div style={{ color: 'var(--muted)', fontSize: 13 }}>No technicians match "{techSearch}"</div>
          )}
          {techSummary.filter(t => visibleTechs.find(v => v.id === t.id)).map(tech => (
            <button key={tech.id} onClick={() => { setActiveTech(tech.id); setTaskSearch(''); setStatusFilter(''); setPriorityFilter('') }}
              style={{
                padding: '7px 14px', borderRadius: 8, border: '1px solid var(--border)',
                background: activeTech === tech.id ? 'var(--primary)' : 'var(--surface2)',
                color: activeTech === tech.id ? '#fff' : 'var(--text)',
                cursor: 'pointer', fontSize: 13, fontWeight: 600,
                display: 'flex', alignItems: 'center', gap: 7
              }}>
              <span>{tech.name}</span>
              <span style={{
                background: activeTech === tech.id ? 'rgba(255,255,255,0.25)' : 'var(--surface)',
                borderRadius: 10, padding: '1px 7px', fontSize: 11, fontWeight: 700
              }}>{tech.total}</span>
              {tech.submitted > 0 && (
                <span style={{ background: 'var(--yellow)', color: '#000', borderRadius: 10, padding: '1px 6px', fontSize: 10, fontWeight: 700 }}>
                  {tech.submitted} review
                </span>
              )}
            </button>
          ))}
        </div>
      </div>

      {/* Active technician info bar */}
      {activeTech && (() => {
        const tech = techSummary.find(t => t.id === activeTech)
        if (!tech) return null
        return (
          <div className="card" style={{ marginBottom: 16, padding: '12px 16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}>
              <div style={{ fontWeight: 700, fontSize: 15 }}>{tech.name}</div>
              <div style={{ fontSize: 12, color: 'var(--muted)' }}>{tech.employee_code}</div>
              <div style={{ marginLeft: 'auto', display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                {[
                  { label: 'Pending',     val: tech.pending,     color: 'var(--yellow)' },
                  { label: 'In Progress', val: tech.in_progress, color: 'var(--orange)' },
                  { label: 'Submitted',   val: tech.submitted,   color: 'var(--cyan)'   },
                  { label: 'Completed',   val: tech.completed,   color: 'var(--green)'  },
                ].map(s => (
                  <div key={s.label} style={{ textAlign: 'center' }}>
                    <div style={{ fontSize: 18, fontWeight: 700, color: s.color }}>{s.val}</div>
                    <div style={{ fontSize: 10, color: 'var(--muted)' }}>{s.label}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )
      })()}

      {/* Task search + filter bar */}
      {activeTech && (
        <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap', alignItems: 'center' }}>
          <input
            placeholder="🔍 Search tasks or schools..."
            value={taskSearch}
            onChange={e => setTaskSearch(e.target.value)}
            style={{ flex: 1, minWidth: 180, padding: '7px 12px', fontSize: 13,
              background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 8, color: 'var(--text)' }}
          />
          <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}
            style={{ padding: '7px 10px', fontSize: 13, borderRadius: 8 }}>
            <option value="">All Statuses</option>
            <option value="pending">Pending</option>
            <option value="in_progress">In Progress</option>
            <option value="submitted">Submitted</option>
            <option value="completed">Completed</option>
          </select>
          <select value={priorityFilter} onChange={e => setPriorityFilter(e.target.value)}
            style={{ padding: '7px 10px', fontSize: 13, borderRadius: 8 }}>
            <option value="">All Priorities</option>
            <option value="high">High</option>
            <option value="medium">Medium</option>
            <option value="low">Low</option>
          </select>
          {(taskSearch || statusFilter || priorityFilter) && (
            <button className="btn btn-outline btn-sm"
              onClick={() => { setTaskSearch(''); setStatusFilter(''); setPriorityFilter('') }}>
              Clear filters
            </button>
          )}
          <span style={{ fontSize: 12, color: 'var(--muted)', whiteSpace: 'nowrap' }}>
            {techTasks.length} task{techTasks.length !== 1 ? 's' : ''}
          </span>
        </div>
      )}

      {/* Status columns for active technician */}
      {techTasks.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: 40, color: 'var(--muted)' }}>
          No tasks assigned to this technician{filterDate ? ` on ${filterDate}` : ''}.
        </div>
      ) : (
        <div className="grid-3">
          {STATUS_ORDER.filter(s => s !== 'completed').concat(['completed']).map(status => (
            <div key={status} className="card">
              <div className="card-title" style={{ textTransform: 'capitalize', display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
                <span>{STATUS_LABEL[status]}</span>
                <span style={{ background: 'var(--surface2)', borderRadius: 10, padding: '1px 8px', fontSize: 11 }}>
                  {grouped[status]?.length || 0}
                </span>
                {status === 'pending' && !filterDate && (
                  <span style={{ fontSize: 10, color: 'var(--muted)', fontWeight: 400, marginLeft: 2 }}>
                    {yesterday} → {today}
                  </span>
                )}
                {status === 'submitted' && !filterDate && (
                  <span style={{ fontSize: 10, color: 'var(--muted)', fontWeight: 400, marginLeft: 2 }}>
                    Today only
                  </span>
                )}
              </div>
              {(grouped[status] || []).map(t => (
                <div key={t.id} style={{
                  background: 'var(--surface2)', border: '1px solid var(--border)',
                  borderRadius: 8, padding: 12, marginBottom: 8
                }}>
                  <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 4 }}>{t.title}</div>
                  {t.school_name && (
                    <div style={{ fontSize: 11, color: 'var(--accent2)', marginBottom: 3 }}>🏫 {t.school_name}</div>
                  )}
                  <div style={{ fontSize: 11, color: 'var(--muted)', marginBottom: 6 }}>
                    {t.due_date && `📅 Due: ${t.due_date}`}
                  </div>
                  <div className="flex gap-8 items-center">
                    <span className={`pill ${PRIORITY_PILL[t.priority] || 'pill-gray'}`} style={{ fontSize: 10 }}>{t.priority}</span>
                    <div style={{ marginLeft: 'auto', display: 'flex', gap: 4 }}>
                      {status === 'pending'     && <button className="btn btn-outline btn-sm" onClick={() => updateStatus(t.id, 'in_progress')}>Start</button>}
                      {status === 'in_progress' && <button className="btn btn-green btn-sm" onClick={() => updateStatus(t.id, 'completed')}>Done</button>}
                      {status === 'submitted'   && (
                        <>
                          <button className="btn btn-green btn-sm" onClick={() => updateStatus(t.id, 'completed')}>✅ Verify</button>
                          <button className="btn btn-danger btn-sm" onClick={() => updateStatus(t.id, 'pending')}>✕ Reject</button>
                        </>
                      )}
                      <button className="btn btn-danger btn-sm" onClick={() => del(t.id)}>×</button>
                    </div>
                  </div>
                </div>
              ))}
              {(grouped[status] || []).length === 0 && (
                <div style={{ color: 'var(--muted)', fontSize: 12, textAlign: 'center', padding: 12 }}>Empty</div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Create Task Modal */}
      {modal && (
        <div className="modal-backdrop">
          <div className="modal-box">
            <button className="modal-close" onClick={() => setModal(false)}>✕</button>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 16 }}>+ Create Task</h3>
            <form onSubmit={save}>
              <div className="form-grid">
                <div className="form-group form-full"><label>Title *</label><input required value={form.title} onChange={f('title')} /></div>
                <div className="form-group form-full"><label>Description</label><textarea value={form.description} onChange={f('description')} /></div>
                <div className="form-group"><label>Assign To *</label>
                  <SearchableSelect value={form.assigned_to_id} onChange={val => setForm({ ...form, assigned_to_id: val })}
                    placeholder="Select…"
                    options={employees.filter(e => e.role === 'technician').map(e => ({ value: String(e.id), label: `${e.name} (${e.employee_code})` }))} />
                </div>
                <div className="form-group"><label>Priority</label>
                  <select value={form.priority} onChange={f('priority')}>
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                  </select>
                </div>
                <div className="form-group form-full"><label>Due Date</label>
                  <input type="date" value={form.due_date} onChange={f('due_date')} />
                </div>
              </div>
              <div className="mt-16 flex gap-8">
                <button type="submit" className="btn btn-primary">Create</button>
                <button type="button" className="btn btn-outline" onClick={() => setModal(false)}>Cancel</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Reset All Tasks confirmation modal */}
      {resetStep === 1 && (
        <div className="modal-backdrop">
          <div className="modal-box" style={{ maxWidth: 440 }}>
            <div style={{ textAlign: 'center', marginBottom: 20 }}>
              <div style={{ fontSize: 48, marginBottom: 8 }}>⚠️</div>
              <h3 style={{ fontSize: 17, fontWeight: 700, color: 'var(--red)', marginBottom: 8 }}>Reset ALL Tasks?</h3>
              <p style={{ fontSize: 13, color: 'var(--muted)', lineHeight: 1.6 }}>
                This will <b style={{ color: 'var(--text)' }}>permanently delete every task</b> across all technicians.
                All pending, in-progress, and submitted tasks will be gone.<br /><br />
                After reset, click <b style={{ color: 'var(--green)' }}>Generate Daily Tasks</b> to assign fresh tasks.
              </p>
            </div>
            <div style={{ marginBottom: 16 }}>
              <label style={{ fontSize: 13, color: 'var(--muted)', display: 'block', marginBottom: 6 }}>
                Type <b style={{ color: 'var(--red)' }}>RESET</b> to confirm:
              </label>
              <input
                autoFocus
                value={resetConfirmText}
                onChange={e => setResetConfirmText(e.target.value)}
                placeholder="Type RESET here"
                style={{ width: '100%', boxSizing: 'border-box', padding: '10px 12px', fontSize: 15,
                  background: 'var(--surface2)', border: `2px solid ${resetConfirmText === 'RESET' ? 'var(--red)' : 'var(--border)'}`,
                  borderRadius: 8, color: 'var(--text)', fontWeight: 700, letterSpacing: 1 }}
              />
            </div>
            <div style={{ display: 'flex', gap: 10 }}>
              <button
                className="btn btn-danger"
                style={{ flex: 1, opacity: resetConfirmText === 'RESET' ? 1 : 0.4 }}
                disabled={resetConfirmText !== 'RESET'}
                onClick={resetAllTasks}
              >
                🗑️ Yes, Delete All Tasks
              </button>
              <button className="btn btn-outline" style={{ flex: 1 }}
                onClick={() => { setResetStep(0); setResetConfirmText('') }}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {toast && <div className="toast">{toast}</div>}
    </div>
  )
}
